package com.example.colorguessinggame.model;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

@Entity
public class Color {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id; // here is our primary key
    private String name;

    public Color() {
    }

    public Color(String name) {
        this.name = name;
    }
    // Getters and setters
    public Long getId() {
        return id;
    }


    public String getName() {
        return name;
    }

    // ID is autogenerated so we don't set the ID
    public void setName(String name) {
        this.name = name;
    }
}
